### ISSUE TITLE
ImportError: No module named interfaces

### ISSUE THREAD

**Issue by davidemoro** [mozilla/PyPOM#12]
If you install pypom 1.1.0 you get an import error:
```
Type "help", "copyright", "credits" or "license" for more information.
>>> import pypom
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/pypom/__init__.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/pypom/page.py", line 8, in <module>
  File "build/bdist.linux-x86_64/egg/pypom/view.py", line 7, in <module>
ImportError: No module named interfaces
```

**Comment by davidemoro** [comment]
If you install the git version all goes fine (with or without optional splinter):
```
pip install -e git+git@github.com:mozilla/PyPOM.git#egg=PyPOM
```

**Comment by davehunt** [comment]
We noticed this too. I'd like to get a fix out as soon as possible, but I'm probably not going to be available to work on it today - are you able to look into it @davidemoro?

**Comment by davidemoro** [comment]
Sure, here I am

**Comment by davidemoro** [comment]
Hi @davehunt,

running ``python setup.py sdist`` from master will produce a ".tar.gz" file that contains all the needed modules, interfaces module too (the one missing on pypi). So it seems that only the 1.1.0 published on pypi is affected so probably something went wrong during the packaging phase.

Can you try another time to rebuild the package? Are you able to see the interfaces module?

**Comment by davidemoro** [comment]
All fine with ``python setup.py sdist`` but ``python setup.py bdist_wheel`` does not include all needed modules:
```
(PYPOM)davide@davide:~/workspaces/PyPOM$ python setup.py bdist_wheel
running bdist_wheel
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/pypom
copying pypom/selenium_driver.py -> build/lib.linux-x86_64-2.7/pypom
copying pypom/__init__.py -> build/lib.linux-x86_64-2.7/pypom
copying pypom/view.py -> build/lib.linux-x86_64-2.7/pypom
copying pypom/page.py -> build/lib.linux-x86_64-2.7/pypom
copying pypom/region.py -> build/lib.linux-x86_64-2.7/pypom
copying pypom/splinter_driver.py -> build/lib.linux-x86_64-2.7/pypom
copying pypom/exception.py -> build/lib.linux-x86_64-2.7/pypom
copying pypom/driver.py -> build/lib.linux-x86_64-2.7/pypom
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/wheel
creating build/bdist.linux-x86_64/wheel/pypom
copying build/lib.linux-x86_64-2.7/pypom/selenium_driver.py -> build/bdist.linux-x86_64/wheel/pypom
copying build/lib.linux-x86_64-2.7/pypom/__init__.py -> build/bdist.linux-x86_64/wheel/pypom
copying build/lib.linux-x86_64-2.7/pypom/view.py -> build/bdist.linux-x86_64/wheel/pypom
copying build/lib.linux-x86_64-2.7/pypom/page.py -> build/bdist.linux-x86_64/wheel/pypom
copying build/lib.linux-x86_64-2.7/pypom/region.py -> build/bdist.linux-x86_64/wheel/pypom
copying build/lib.linux-x86_64-2.7/pypom/splinter_driver.py -> build/bdist.linux-x86_64/wheel/pypom
copying build/lib.linux-x86_64-2.7/pypom/exception.py -> build/bdist.linux-x86_64/wheel/pypom
copying build/lib.linux-x86_64-2.7/pypom/driver.py -> build/bdist.linux-x86_64/wheel/pypom
running install_egg_info
running egg_info
writing requirements to PyPOM.egg-info/requires.txt
writing PyPOM.egg-info/PKG-INFO
writing top-level names to PyPOM.egg-info/top_level.txt
writing dependency_links to PyPOM.egg-info/dependency_links.txt
writing manifest file 'PyPOM.egg-info/SOURCES.txt'
Copying PyPOM.egg-info to build/bdist.linux-x86_64/wheel/PyPOM-1.1.0-py2.7.egg-info
running install_scripts
creating build/bdist.linux-x86_64/wheel/PyPOM-1.1.0.dist-info/WHEEL
```

**Comment by davidemoro** [comment]
More info here:
* https://packaging.python.org/distributing/#manifest-in
* https://docs.python.org/3.4/distutils/sourcedist.html#specifying-the-files-to-distribute

**Comment by davidemoro** [comment]
Pull request ready to be reviewed

**Comment by davehunt** [comment]
Sorry, I didn't notice your pull request. This should be fixed in https://github.com/mozilla/PyPOM/commit/ef5896feff41049c327b5a478eb6cc3783e488a2. I've tagged v1.1.1 so once Travis CI is complete we should have a new release.
