### ISSUE TITLE
Unable to use PyPOM with a Selenium Driver wrapped in EventFiringWebDriver

### ISSUE THREAD

**Issue by Greums** [mozilla/PyPOM#75]
I would like to use Selenium driver with event firing support, but PyPOM seems to fail at initialization with such configuration:

```python
from selenium.webdriver import Chrome
from selenium.webdriver.common.by import By
from selenium.webdriver.support.events import EventFiringWebDriver, \
    AbstractEventListener

from pypom import Page


class Qwant(Page):

    _search_input_locator = (By.XPATH, '//input[@name="q"]')

    def wait_for_page_to_load(self):
        search_input = self.find_element(*self._search_input_locator)
        self.wait.until(lambda _: search_input.is_enabled())


class ExceptionListener(AbstractEventListener):
    def on_exception(self, exc, driver):
        driver.get_screenshot_as_file('exception.png')


def main():
    driver = Chrome()
    ef_driver = EventFiringWebDriver(driver, ExceptionListener())
    page = Qwant(ef_driver, base_url='https://www.qwant.com/')
    page.open()


if __name__ == '__main__':
    main()
```

Here's the resulting traceback:

```bash
Traceback (most recent call last):
  File "PyPOM_EventFiringWebDriver.py", line 30, in <module>
    main()
  File "PyPOM_EventFiringWebDriver.py", line 26, in main
    Qwant(ef_driver, base_url='https://www.qwant.com/')
  File "/home/damienlebourdonnec/.virtualenvs/tmp-41cf2100534a6a0/local/lib/python2.7/site-packages/pypom/page.py", line 72, in __init__
    super(Page, self).__init__(driver, timeout)
  File "/home/damienlebourdonnec/.virtualenvs/tmp-41cf2100534a6a0/local/lib/python2.7/site-packages/pypom/view.py", line 14, in __init__
    self.driver_adapter = IDriver(driver)
  File "/home/damienlebourdonnec/.virtualenvs/tmp-41cf2100534a6a0/local/lib/python2.7/site-packages/zope/component/hookable.py", line 33, in __call__
    return self.__implementation(*args, **kw)
  File "/home/damienlebourdonnec/.virtualenvs/tmp-41cf2100534a6a0/local/lib/python2.7/site-packages/zope/component/_api.py", line 156, in adapter_hook
    return sitemanager.queryAdapter(object, interface, name, default)
  File "/home/damienlebourdonnec/.virtualenvs/tmp-41cf2100534a6a0/local/lib/python2.7/site-packages/zope/interface/registry.py", line 348, in queryAdapter
    return self.adapters.queryAdapter(object, interface, name, default)
  File "/home/damienlebourdonnec/.virtualenvs/tmp-41cf2100534a6a0/local/lib/python2.7/site-packages/zope/interface/adapter.py", line 539, in _uncached_lookup
    order)
  File "/home/damienlebourdonnec/.virtualenvs/tmp-41cf2100534a6a0/local/lib/python2.7/site-packages/zope/interface/adapter.py", line 672, in _lookup
    for spec in specs[i].__sro__:
AttributeError: 'function' object has no attribute '__sro__'
```

Is there a trick to support EventFiringWebDriver like a normal Selenium Driver ?

Thx

**Comment by Greums** [comment]
My bad, I found a simple solution to make it work :smile:

**Comment by davehunt** [comment]
Awesome, I love it when an issue turns into a pull request! I'll review, and hopefully merge/release later today. Thanks!

**Comment by davehunt** [comment]
PyPOM 1.3.0 has [been released](https://pypi.python.org/pypi/PyPOM/1.3.0).

**Comment by Greums** [comment]
Thank you for this quick release, and thanks too for this library, it's really helpfull ! :sparkles:
